package view;

import javax.swing.JFrame;
import view.bairro.FormBairro;
import view.caixa.FormCaixa;
import view.categoria.FormCategoria;
import view.cidade.FormCidade;
import view.fornecedor.FormFornecedor;
import view.cliente.ListCliente;
import view.gerente.FormGerente;
import view.logradouro.ListLogradouro;
import view.produto.ListProduto;
import view.unidade.FormUnidade;
import view.usuario.FormUsuario;
import view.vendedor.FormVendedor;

/**
 *
 * @author ander
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastrar = new javax.swing.JMenu();
        jMnProdutos = new javax.swing.JMenu();
        jMnProdutosListar = new javax.swing.JMenuItem();
        jMnUnidades = new javax.swing.JMenuItem();
        jMnCategorias = new javax.swing.JMenuItem();
        jMnClientes = new javax.swing.JMenuItem();
        jMnFornecedores = new javax.swing.JMenuItem();
        jMnLogradouros = new javax.swing.JMenu();
        jMnLogradourosListar = new javax.swing.JMenuItem();
        jMnLogradourosBairros = new javax.swing.JMenuItem();
        jMnLogradourosCidades = new javax.swing.JMenuItem();
        jMnFuncionarios = new javax.swing.JMenu();
        jMnFuncionariosGerentes = new javax.swing.JMenuItem();
        jMnFuncionariosVendedores = new javax.swing.JMenuItem();
        jMnFuncionariosCaixa = new javax.swing.JMenuItem();
        jMnUsuarios = new javax.swing.JMenuItem();
        jFaturamento = new javax.swing.JMenu();
        jConfiguracoes = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Estoque 1.0");

        jCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jCadastrar.setText("Cadastrar");
        jCadastrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMnProdutos.setForeground(new java.awt.Color(0, 0, 0));
        jMnProdutos.setText("Produtos");
        jMnProdutos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jMnProdutosListar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnProdutosListar.setForeground(new java.awt.Color(0, 0, 0));
        jMnProdutosListar.setText("Listar");
        jMnProdutosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnProdutosListarActionPerformed(evt);
            }
        });
        jMnProdutos.add(jMnProdutosListar);

        jMnUnidades.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnUnidades.setForeground(new java.awt.Color(0, 0, 0));
        jMnUnidades.setText("Unidades");
        jMnUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUnidadesActionPerformed(evt);
            }
        });
        jMnProdutos.add(jMnUnidades);

        jMnCategorias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnCategorias.setForeground(new java.awt.Color(0, 0, 0));
        jMnCategorias.setText("Categorias");
        jMnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCategoriasActionPerformed(evt);
            }
        });
        jMnProdutos.add(jMnCategorias);

        jCadastrar.add(jMnProdutos);

        jMnClientes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnClientes.setForeground(new java.awt.Color(0, 0, 0));
        jMnClientes.setText("Clientes");
        jMnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClientesActionPerformed(evt);
            }
        });
        jCadastrar.add(jMnClientes);

        jMnFornecedores.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnFornecedores.setForeground(new java.awt.Color(0, 0, 0));
        jMnFornecedores.setText("Fornecedores");
        jMnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnFornecedoresActionPerformed(evt);
            }
        });
        jCadastrar.add(jMnFornecedores);

        jMnLogradouros.setForeground(new java.awt.Color(0, 0, 0));
        jMnLogradouros.setText("Logradouros");
        jMnLogradouros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jMnLogradourosListar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnLogradourosListar.setForeground(new java.awt.Color(0, 0, 0));
        jMnLogradourosListar.setText("Listar");
        jMnLogradourosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnLogradourosListarActionPerformed(evt);
            }
        });
        jMnLogradouros.add(jMnLogradourosListar);

        jMnLogradourosBairros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnLogradourosBairros.setForeground(new java.awt.Color(0, 0, 0));
        jMnLogradourosBairros.setText("Bairros");
        jMnLogradourosBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnLogradourosBairrosActionPerformed(evt);
            }
        });
        jMnLogradouros.add(jMnLogradourosBairros);

        jMnLogradourosCidades.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnLogradourosCidades.setForeground(new java.awt.Color(0, 0, 0));
        jMnLogradourosCidades.setText("Cidades");
        jMnLogradourosCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnLogradourosCidadesActionPerformed(evt);
            }
        });
        jMnLogradouros.add(jMnLogradourosCidades);

        jCadastrar.add(jMnLogradouros);

        jMnFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        jMnFuncionarios.setText("Funcionários");
        jMnFuncionarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jMnFuncionariosGerentes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnFuncionariosGerentes.setForeground(new java.awt.Color(0, 0, 0));
        jMnFuncionariosGerentes.setText("Gerentes");
        jMnFuncionariosGerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnFuncionariosGerentesActionPerformed(evt);
            }
        });
        jMnFuncionarios.add(jMnFuncionariosGerentes);

        jMnFuncionariosVendedores.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnFuncionariosVendedores.setForeground(new java.awt.Color(0, 0, 0));
        jMnFuncionariosVendedores.setText("Vendedores");
        jMnFuncionariosVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnFuncionariosVendedoresActionPerformed(evt);
            }
        });
        jMnFuncionarios.add(jMnFuncionariosVendedores);

        jMnFuncionariosCaixa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnFuncionariosCaixa.setForeground(new java.awt.Color(0, 0, 0));
        jMnFuncionariosCaixa.setText("Caixas");
        jMnFuncionariosCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnFuncionariosCaixaActionPerformed(evt);
            }
        });
        jMnFuncionarios.add(jMnFuncionariosCaixa);

        jCadastrar.add(jMnFuncionarios);

        jMnUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMnUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jMnUsuarios.setText("Usuários");
        jMnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUsuariosActionPerformed(evt);
            }
        });
        jCadastrar.add(jMnUsuarios);

        jMenuBar1.add(jCadastrar);

        jFaturamento.setForeground(new java.awt.Color(0, 0, 0));
        jFaturamento.setText("Faturamento");
        jMenuBar1.add(jFaturamento);

        jConfiguracoes.setForeground(new java.awt.Color(0, 0, 0));
        jConfiguracoes.setText("Configurações");
        jConfiguracoes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem9.setText("Empresa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jConfiguracoes.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem10.setText("Parâmetros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jConfiguracoes.add(jMenuItem10);

        jMenuSair.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jMenuSair.setForeground(new java.awt.Color(0, 0, 0));
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jConfiguracoes.add(jMenuSair);

        jMenuBar1.add(jConfiguracoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnFornecedoresActionPerformed
        FormFornecedor dialog = new FormFornecedor(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnFornecedoresActionPerformed

    private void jMnProdutosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnProdutosListarActionPerformed
        ListProduto dialog = new ListProduto(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnProdutosListarActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMnUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUnidadesActionPerformed
       FormUnidade dialog = new FormUnidade(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_jMnUnidadesActionPerformed

    private void jMnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCategoriasActionPerformed
        FormCategoria dialog = new FormCategoria(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnCategoriasActionPerformed

    private void jMnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClientesActionPerformed
        ListCliente dialog = new ListCliente(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnClientesActionPerformed

    private void jMnFuncionariosGerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnFuncionariosGerentesActionPerformed
        FormGerente dialog = new FormGerente(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnFuncionariosGerentesActionPerformed

    private void jMnLogradourosCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnLogradourosCidadesActionPerformed
        FormCidade dialog = new FormCidade(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnLogradourosCidadesActionPerformed

    private void jMnLogradourosBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnLogradourosBairrosActionPerformed
        FormBairro dialog = new FormBairro(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnLogradourosBairrosActionPerformed

    private void jMnLogradourosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnLogradourosListarActionPerformed
        ListLogradouro dialog = new ListLogradouro(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnLogradourosListarActionPerformed

    private void jMnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUsuariosActionPerformed
        FormUsuario dialog = new FormUsuario(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnUsuariosActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMnFuncionariosVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnFuncionariosVendedoresActionPerformed
        FormVendedor dialog = new FormVendedor(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnFuncionariosVendedoresActionPerformed

    private void jMnFuncionariosCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnFuncionariosCaixaActionPerformed
        FormCaixa dialog = new FormCaixa(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMnFuncionariosCaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCadastrar;
    private javax.swing.JMenu jConfiguracoes;
    private javax.swing.JMenu jFaturamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMnCategorias;
    private javax.swing.JMenuItem jMnClientes;
    private javax.swing.JMenuItem jMnFornecedores;
    private javax.swing.JMenu jMnFuncionarios;
    private javax.swing.JMenuItem jMnFuncionariosCaixa;
    private javax.swing.JMenuItem jMnFuncionariosGerentes;
    private javax.swing.JMenuItem jMnFuncionariosVendedores;
    private javax.swing.JMenu jMnLogradouros;
    private javax.swing.JMenuItem jMnLogradourosBairros;
    private javax.swing.JMenuItem jMnLogradourosCidades;
    private javax.swing.JMenuItem jMnLogradourosListar;
    private javax.swing.JMenu jMnProdutos;
    private javax.swing.JMenuItem jMnProdutosListar;
    private javax.swing.JMenuItem jMnUnidades;
    private javax.swing.JMenuItem jMnUsuarios;
    // End of variables declaration//GEN-END:variables
}
