/**
 * Liberar Crédito
 * Autorizar venda acima do limite
 * Cancelar venda
 * Sangria de caixa
 */
package view.gerente;

import Helpers.TeclasAtalho;
import control.GerenteControl;
import control.UsuarioControl;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.Gerente;
import model.Usuario;

/**
 *
 * @author ander
 */
public class FormGerente extends javax.swing.JDialog {
    
    private List<Gerente> gerentes;
    public boolean success;
    /**
     * Creates new form FormGerente
     */
    public FormGerente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.gerentes = new ArrayList<>();
        
        this.success = false;
        
        /**muda estilo da header da tabela**/
        new components.TableHeader(jTable.getTableHeader());
        
        //rotina para o dialog fechar com a tecla ESC
        this.getRootPane()
                .registerKeyboardAction(
                        e -> { this.dispose(); },
                        KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), 
                        JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        iUser.loadOptions((List<Object>) (Object) new UsuarioControl().getAll(), (Object) "Selecione...");
        
        jTable.requestFocus();
        
        this.loadJtable();
        
        this.cancelForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iCodigo = new components.inputs.InputInt();
        iNome = new components.inputs.Input();
        iSenha = new components.inputs.InputPassword();
        iDesconto = new components.inputs.InputDouble();
        iCk_excederDesconto = new javax.swing.JCheckBox();
        iCk_liberarVendas = new javax.swing.JCheckBox();
        iCk_excederLimite = new javax.swing.JCheckBox();
        iCk_cancelarVenda = new javax.swing.JCheckBox();
        iLimite = new components.inputs.InputDouble();
        iUser = new components.selecter.InputSelect();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerentes Cadastrados");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iCodigo.setInputLabel("Código");
        iCodigo.setInputText("");

        iNome.setInputLabel("Nome");
        iNome.setInputText("");

        iSenha.setInputLabel("Senha");
        iSenha.setInputText("");

        iDesconto.setInputLabel("Desconto %");

        iCk_excederDesconto.setBackground(new java.awt.Color(255, 255, 255));
        iCk_excederDesconto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        iCk_excederDesconto.setForeground(new java.awt.Color(42, 77, 104));
        iCk_excederDesconto.setText("Exceder Desconto Máximo");
        iCk_excederDesconto.setPreferredSize(new java.awt.Dimension(150, 20));
        iCk_excederDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCk_excederDescontoActionPerformed(evt);
            }
        });

        iCk_liberarVendas.setBackground(new java.awt.Color(255, 255, 255));
        iCk_liberarVendas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        iCk_liberarVendas.setForeground(new java.awt.Color(42, 77, 104));
        iCk_liberarVendas.setText("Liberar Todas as Vendas");
        iCk_liberarVendas.setPreferredSize(new java.awt.Dimension(150, 20));
        iCk_liberarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCk_liberarVendasActionPerformed(evt);
            }
        });

        iCk_excederLimite.setBackground(new java.awt.Color(255, 255, 255));
        iCk_excederLimite.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        iCk_excederLimite.setForeground(new java.awt.Color(42, 77, 104));
        iCk_excederLimite.setText("Exceder Limite Máximo");
        iCk_excederLimite.setPreferredSize(new java.awt.Dimension(150, 20));
        iCk_excederLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCk_excederLimiteActionPerformed(evt);
            }
        });

        iCk_cancelarVenda.setBackground(new java.awt.Color(255, 255, 255));
        iCk_cancelarVenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        iCk_cancelarVenda.setForeground(new java.awt.Color(42, 77, 104));
        iCk_cancelarVenda.setText("Cancelar venda");
        iCk_cancelarVenda.setPreferredSize(new java.awt.Dimension(150, 20));
        iCk_cancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCk_cancelarVendaActionPerformed(evt);
            }
        });

        iLimite.setInputLabel("Limite Máximo");

        iUser.setInputLabel("Usuário Vinculado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(iCk_liberarVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(iCk_excederDesconto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iCk_excederLimite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iCk_cancelarVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iCk_excederDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iCk_excederLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iCk_liberarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iCk_cancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNovo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setPreferredSize(new java.awt.Dimension(110, 30));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setPreferredSize(new java.awt.Dimension(110, 30));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setPreferredSize(new java.awt.Dimension(110, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDeletar.setText("BLOQUEAR");
        btnDeletar.setActionCommand("");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setPreferredSize(new java.awt.Dimension(110, 30));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Bloqueado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable.setRowHeight(20);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //habilita form
        this.newForm();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        int id = iCodigo.getValue();
        String nome = iNome.getInputText();
        String senha = iSenha.getInputText();
        double descontoMaximo = iDesconto.getValue();
        double limiteMaximo = iLimite.getValue();
        Usuario usuarioVinculado = (iUser.getSelectedIndex()== 0) ? null : (Usuario) iUser.getSelectedItem();
        boolean excederDesconto = iCk_excederDesconto.isSelected();
        boolean excederLimite = iCk_excederLimite.isSelected();
        boolean liberarTodasVendas = iCk_liberarVendas.isSelected();
        boolean cancelarVenda = iCk_cancelarVenda.isSelected();

        GerenteControl control = new GerenteControl();

        if(control.save(id, nome, senha, descontoMaximo, limiteMaximo, usuarioVinculado, excederDesconto, excederLimite, liberarTodasVendas, cancelarVenda)){
            this.success = true;

            components.Message.show(null,"Gerente registrado com sucesso.");
            this.loadJtable();
            this.cancelForm();

        }else{
            this.success = false;
        }

        control.closeConection();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(this.btnSalvar.isEnabled()){//se o botão salvar estiver ativado
            this.cancelForm();
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int id = iCodigo.getValue();
        if(id > 0){
            GerenteControl control = new GerenteControl();
            if(control.toggleAtive(id)){
                this.success = true;
                this.loadJtable();
                this.cancelForm();
            }else{
                components.Message.show(null, "Falha ao registrar!");
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void iCk_excederDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCk_excederDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCk_excederDescontoActionPerformed

    private void iCk_liberarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCk_liberarVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCk_liberarVendasActionPerformed

    private void iCk_excederLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCk_excederLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCk_excederLimiteActionPerformed

    private void iCk_cancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCk_cancelarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCk_cancelarVendaActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if(evt.getClickCount() == 2){
            this.loadForm();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyPressed
        if(TeclasAtalho.TECLA_ENTER(evt)){
            evt.consume();
            loadForm();
        }
    }//GEN-LAST:event_jTableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormGerente dialog = new FormGerente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox iCk_cancelarVenda;
    private javax.swing.JCheckBox iCk_excederDesconto;
    private javax.swing.JCheckBox iCk_excederLimite;
    private javax.swing.JCheckBox iCk_liberarVendas;
    private components.inputs.InputInt iCodigo;
    private components.inputs.InputDouble iDesconto;
    private components.inputs.InputDouble iLimite;
    private components.inputs.Input iNome;
    private components.inputs.InputPassword iSenha;
    private components.selecter.InputSelect iUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    
    private void loadJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

        modelo.setRowCount(0);

        gerentes.clear();
        GerenteControl control = new GerenteControl();
        
        control.getAll().forEach(p -> {
            gerentes.add(p);
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                (p.isBloqueado()) ? "Bloqueado" : "Normal"
            });
        });
        
        //uControl.closeConection();
    }
    
    private void cancelForm() {
        //desabilita a entrada de dados na input
        iCodigo.readOnly(true);
        iCodigo.setInputText("");
        
        iNome.readOnly(true);
        iNome.setInputText("");
        
        iSenha.readOnly(true);
        iSenha.setInputText("");
        
        iDesconto.readOnly(true);
        iDesconto.setInputText("0,00");
        
        iLimite.readOnly(true);
        iLimite.setInputText("0,00");
        
        iUser.readOnly(true);
        iUser.setSelectedIndex(0);
        
        iCk_excederDesconto.setSelected(false);
        iCk_excederLimite.setSelected(false);
        iCk_liberarVendas.setSelected(false);
        iCk_cancelarVenda.setSelected(false);
        
        this.btnSalvar.setEnabled(false);
        this.btnDeletar.setEnabled(false);
        this.btnNovo.setEnabled(true);
        
        this.jTable.setEnabled(true);
        this.jTable.requestFocus();
        this.btnDeletar.setText("BLOQUEAR");
        this.btnCancelar.setText("FECHAR"); 
    }
    
    private void newForm() {
        //desabilita a entrada de dados na input
        iSenha.readOnly(false);
        
        iDesconto.readOnly(false);
        
        iLimite.readOnly(false);
        
        iUser.readOnly(false);
        
        iNome.readOnly(false);
        
        iNome.requestFocus();
        
        this.btnNovo.setEnabled(false);
        this.btnSalvar.setEnabled(true);
        this.btnDeletar.setEnabled(false);
        
        this.jTable.setEnabled(false);
        
        this.btnCancelar.setText("CANCELAR");
        
    }
    
    private void editForm(){
        this.newForm();
        this.btnDeletar.setEnabled(true);
    }
    
    //carregar o formulario para edição
    private void loadForm() {
        int index =  jTable.getSelectedRow();
        if(index > -1){
            Gerente u = gerentes.get(index);
            this.editForm();
            
            this.iCodigo.setInputText(u.getId());
            this.iNome.setInputText(u.getNome());
            iSenha.setInputText(u.getSenha());
            iDesconto.setInputText(u.getDescontoMaximo());
            iLimite.setInputText(u.getLimiteMaximo());
            
            iUser.setSelectedItem((Object) u.getUsuarioVinculado());
            
            iCk_excederDesconto.setSelected(u.isExcederDesconto());
            iCk_excederLimite.setSelected(u.isExcederLimite());
            iCk_liberarVendas.setSelected(u.isLiberarTodasVendas());
            iCk_cancelarVenda.setSelected(u.isCancelarVenda());
            
            if(u.isBloqueado()){
                this.btnDeletar.setText("DESBLOQUEAR");
            }
        }
        
    }
}
